image: golang:1.10.4

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update && apt-get install -y libltdl-dev
            - source bitbucket-pipelines-go.sh
            - cd ${IMPORT_PATH}
            - sh bitbucket-pipelines-tests.sh
